on: [push]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.2'
    - run: git config --global user.email "test@test.test"
    - run: git config --global user.name "mob test git user"
    - run: go test
