on: release
name: Release
jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu, darwin, windows]
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: remotemobprogramming/go-release.action@go1.14.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: ${{ matrix.os }}