on:
  release:
    types: [published]
name: Release
jobs:
  release:
    strategy:
      matrix:
        os: [linux, darwin, windows]
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      - name: Get Release
        id: release
        uses: bruceadams/get-release@v1
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.4'
      - run: git config --global user.email "test@test.test"
      - run: git config --global user.name "${{github.actor}}"
      - run: go test
      - name: Build and create release artifacts using .github/build
        uses: skx/github-action-build@master
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GOARCH: amd64
          GOOS: ${{ matrix.os }}
      - name: Upload artifacts to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "*.tar.gz"
          tag: ${{ steps.get_version.outputs.version }}
          file_glob: true
      - name: Set SHA
        if: matrix.os == 'darwin'
        id: shasum
        run: |
          echo ::set-output name=sha::"$(shasum -a 256 *.tar.gz | awk '{printf $1}')"
      - name: Bump homebrew formula
        if: matrix.os == 'darwin'
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{ secrets.HOMEBREW }}
        run: |
          brew tap ${{github.repository_owner}}/homebrew-brew
          brew bump-formula-pr -f --version=${{ steps.get_version.outputs.version }} --no-browse --no-audit \
          --sha256=${{ steps.shasum.outputs.sha }} \
          --url="https://github.com/${{github.repository_owner}}/mob/releases/download/${{ steps.get_version.outputs.version }}/mob_${{steps.get_version.outputs.version}}_darwin_amd64.tar.gz" \
          ${{github.repository_owner}}/homebrew-brew/mob